create make_table_02 ARD function.
pharmaverse/cardinal pull request #219
Opened 2024-05-23 17:32 UTC by ayogasekaram

Initial commit
- create the ARD function, make table generation functions internal.

2025-02-12 10:11 UTC, jknizia requested changes
Hi @ayogasekaram, thanks for adding me to the PR. I found a couple of minor issues. Please see comments in the code. BR

2025-02-12 10:11 UTC, jknizia commented on R/fda-table_02.R
> +                          denominator = NULL,
`denominator` is never used in `make_table_02()` and I don't think it would add any benefit to this particular table. Please consider to remove it.

2025-02-12 10:11 UTC, jknizia commented on R/fda-table_02.R
> +                                  alt_counts_df = NULL,
I feel like `alt_counts_df` adds no value to this particular table. What do you think?

2025-02-12 10:11 UTC, jknizia commented on R/fda-table_02.R
> +#' tbl_rtables <- cardinal:::make_table_05_rtables(df = adsl)
Two comments on the example:
- Since you exported the function, you could remove `cardinal:::` (it is cleaner to remove anyway).
- The example uses the function to produce Table 5. Should be Table 2 :)

2025-02-12 10:11 UTC, jknizia commented on quarto/getting_started.qmd
>    lbl_vars = c("Sex", "Age, years", "Race", "Country of Participation", "Baseline Temperature (C)"),
Please update arguments in this code chunk. It throws an error

2025-02-12 10:11 UTC, jknizia commented on quarto/getting_started.qmd
>    lbl_vars = c("Sex", "Age, years", "Race", "Country of Participation", "Baseline Temperature (C)"),
Also in the next code chunk

2025-02-12 10:11 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
>    vars = c("SEX", "AGE", "AGEGR1", "RACE", "ETHNIC", "COUNTRY", "AVAL"),
Please remove "AVAL". It throws an error by the assertion

2025-02-12 10:11 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +  vars = c("SEX", "AGE", "AGEGR1", "RACE", "ETHNIC", "COUNTRY", "AVAL")
Here as well, please remove AVAL

2025-02-12 10:11 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +print(result$ard, columns = "all", n = Inf)
The `print()` brings: "invalid 'na.print' specification". This can be solved by removing `n = Inf`

2025-02-12 10:11 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
>    lbl_vars = c(
Please update function call to `make_table_02_rtables`

2025-02-12 10:11 UTC, jknizia commented on R/fda-table_02.R
> +#' @inheritParams tbl_make_table_02
This link does not exist. Please update to `make_table_02`

2025-02-12 10:11 UTC, jknizia commented on R/fda-table_02.R
> +#' @inheritParams tbl_make_table_02
Also for `@seealso`

2025-02-12 22:24 UTC, ayogasekaram commented
Thank you so much for your review @jknizia! Much appreciated :) 
I believe I've addressed all of the comments but if there's anything else that needs to be fixed - please let me know.

2025-02-17 06:58 UTC, jknizia requested changes
Dear @ayogasekaram, thank you so much for the update. I found only a few other notes :)

2025-02-17 06:58 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
>  make_table_02(
Not sure whether this is only me, but... If I run this example, no table is produced. If I instead assign the make_table_02() call to a variable and then call the variable, the table is produced. Could you please double check this behavior from your end?

2025-02-17 06:58 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +| `denominator` | (`character`) Alternative dataset used only to calculate column counts. | `NULL` |
Please remove `denominator` entry from this table

2025-02-17 06:58 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +| `alt_counts_df` | (`character`) Alternative dataset used only to calculate column counts. | `NULL` |
Please remove `alt_counts_df` entry

2025-02-17 06:58 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +| `.stats` | (`character`) Statistics to include in the table. Includes statistics for all variable types (only the statistics that are valid for a given variable's type will be printed). See [`tern:
Please remove `.stats` entry, as it is not used within the rtable producing function

2025-02-17 06:58 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +| `.formats` | (named `list` of `character`) List of formats corresponding to each value in `.stats`. Each name is a value in `.stats` and the corresponding value is the format that should be applied
Please remove `.formats` entry, as it is not used within the rtable producing function

2025-02-19 22:14 UTC, edelarua reviewed
Hi @ayogasekaram,

A few additional comments from me but it looks great!!

2025-02-19 22:14 UTC, edelarua commented on R/fda-table_02.R
>    }
This will fix the no output that Jessica noticed.
```suggestion
  if (return_ard) {
    ard <- gtsummary::gather_ard(tbl)
    res <- list(tbl = tbl, ard = ard)
  } else {
    res <- list(tbl = tbl)
  }
```

2025-02-19 22:14 UTC, edelarua commented on quarto/table-templates/template-table_02.qmd
No label for new variable
```suggestion
attr(adsl$AGEGR1, "label") <- "Age Group"

```

2025-02-26 08:23 UTC, jknizia approved these changes
Hi @ayogasekaram, thanks for the updates. I added one further recommendation, but since it is not essential for the functions to work, I approve already.

2025-02-26 08:23 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
>  make_table_02(
It works now, thanks!

2025-02-26 08:23 UTC, jknizia commented on quarto/table-templates/template-table_02.qmd
> +  return_ard = FALSE
It seems like the gtsummary table example produces not quite the same table as the rtables table example. There is an additional parameter "Baseline Temperature" displayed in the rtables example. Could you align the two examples, please?

2025-02-26 21:50 UTC, ayogasekaram commented on quarto/table-templates/template-table_02.qmd
> +  return_ard = FALSE
great call, Jessica! I've added the AVAL to all examples since the demographics table should analyze some baseline characteristics as well :)

2025-03-05 06:56 UTC, jknizia approved these changes

2025-03-18 12:26 UTC, merged